import type { PublicRoomView } from "../lib/types";

export function roomView(
  overrides: Partial<PublicRoomView> = {},
): PublicRoomView {
  return {
    apiVersion: "1",
    roomId: "room-a",
    revision: 7,
    presenceVersion: 0,
    status: "WAITING_FOR_PLAYERS",
    rulesetId: "singapore",
    rulesetVersion: "0.1.0",
    stateSchemaVersion: 2,
    capabilities: [
      "multiplayerLobby",
      "roomEvents",
      "hibernatingWebSockets",
    ],
    config: {
      shooterMode: false,
      minimumFan: 1,
      maximumFan: 5,
      payoutTable: [1, 2, 4, 8, 16, 32],
      kongOnePayment: 2,
      kongThreePayment: 2,
      completeAnimalSetPayment: 4,
      completeFlowerSetPayment: 4,
      completeSeasonSetPayment: 4,
      animalPairPayment: 2,
      flowerSeasonPairPayment: 2,
      initialThirteenPairPayment: 4,
      freshDiscardThreshold: 4,
      freshKongThreshold: 7,
      sevenPairsEnabled: false,
      freshKongPayAllEnabled: false,
      kongFourRobberyEnabled: false,
      concealedSelfDrawBonusEnabled: false,
      automaticDragonWinsEnabled: true,
      automaticWindWinsEnabled: true,
      extraSelfDrawPoints: 0,
    },
    viewerPlayerId: "player-host",
    serverTimeMs: 1_700_000_000_000,
    deadlineMs: null,
    windowId: null,
    players: [
      {
        playerId: "player-host",
        displayName: "Mei",
        role: "HOST",
        ready: false,
        connectionStatus: "CONNECTED",
        disconnectExpiresAtMs: null,
      },
    ],
    seats: [
      {
        view: "opponent",
        seatId: "seat-3",
        slot: 3,
        wind: null,
        occupant: null,
        concealedTileCount: 0,
        hasDrawnTile: false,
        melds: [],
        bonusTiles: [],
      },
      {
        view: "self",
        seatId: "seat-0",
        slot: 0,
        wind: null,
        occupant: {
          controllerType: "external",
          displayName: "Mei",
          playerId: "player-host",
          role: "HOST",
          ready: false,
        },
        concealedTiles: [],
        drawnTile: null,
        melds: [],
        bonusTiles: [],
      },
      {
        view: "opponent",
        seatId: "seat-2",
        slot: 2,
        wind: null,
        occupant: {
          controllerType: "automated",
          displayName: "Bot Bamboo",
          playerId: null,
          role: null,
          ready: true,
        },
        concealedTileCount: 0,
        hasDrawnTile: false,
        melds: [],
        bonusTiles: [],
      },
      {
        view: "opponent",
        seatId: "seat-1",
        slot: 1,
        wind: null,
        occupant: null,
        concealedTileCount: 0,
        hasDrawnTile: false,
        melds: [],
        bonusTiles: [],
      },
    ],
    game: null,
    actions: [
      {
        actionId: "opaque-ready-id",
        label: "Ready",
        enabled: true,
        tone: "primary",
        disabledReason: null,
        presentationSlot: "roomActions",
      },
      {
        actionId: "opaque-rotate-id",
        label: "Create New Invitation Link",
        enabled: true,
        tone: null,
        disabledReason: null,
        presentationSlot: "invitation",
      },
    ],
    ...overrides,
  };
}
